[OPS-8] As a Team Owner I Should Be Able To Connect My Team to Jira via the API
craftcodery/ops-dash-api pull request #3
Opened 2023-01-26 20:53 UTC by chuckgreenman

### Description:

This PR addresses a Jira Issue:

- [[OPS-8] As a Team Owner I Should Be Able To Connect My Team to Jira via the API](https://craftcodery.atlassian.net/browse/OPS-8)

A description of some changes made:

- Adds a migration that add columns for Jira API credentials
- Adds a migration that adds a column for Jira project ids on the projects table
- Requires [lesstif/jira-cloud-restapi](https://github.com/lesstif/php-JiraCloud-RESTAPI).
- Adds a command that updates and creates projects for all teams that have jira credentials set.
- Update team factory to fill our newly added fields.
- Adds a test for the Update or create command.

### Development Checklist:

- [x] The task(s) being resolved have been assigned in Jira.
- [x] Automated tests have been written to cover the changes made in this PR.
- [x] Changes have been tested on a staging or local development environment.

2023-01-26 22:07 UTC, aaronhuisinga requested changes
This looks really good. Just some refactoring requests to help keep things organized as we add more features.

2023-01-26 22:07 UTC, aaronhuisinga commented on app/Console/Commands/PullJiraProjectInformation.php
> +        $teams = Team::whereNotNull('jira_api_token')
This would be a great place for a scope on the Team class. Something like `hasJiraIntegration` that can be reused. Same with Toggl as well actually.

2023-01-26 22:07 UTC, aaronhuisinga commented on app/Console/Commands/PullJiraProjectInformation.php
> +        $teams->map(function ($team) {
`$team` can be type hinted here as `(Team $team)` I believe which would help the IDE with the properties being referenced in the map.

2023-01-26 22:07 UTC, aaronhuisinga commented on app/Console/Commands/PullJiraProjectInformation.php
> +            ));
We will likely be using this logic a lot. Maybe add a `HasJiraIntegration` trait that contains the scope suggested above and a method for the ArrayConfiguration that can be called anywhere we will be using Jira features.

2023-01-26 22:07 UTC, aaronhuisinga commented on app/Console/Commands/PullJiraProjectInformation.php
> +    protected $signature = 'jira:pullprojects';
I think we will end up doing more Jira commands within the projects namespace. Change this to `jira:projects:sync`.

2023-01-27 14:42 UTC, chuckgreenman commented on app/Console/Commands/PullJiraProjectInformation.php
> +        $teams = Team::whereNotNull('jira_api_token')
Added jira and toggl configuration scopes and refactored both commands.

2023-01-27 14:59 UTC, chuckgreenman commented
@aaronhuisinga Feedback is addressed and this is ready for review again!

2023-01-27 16:19 UTC, aaronhuisinga approved these changes

2023-01-27 16:20 UTC, merged